### ISSUE TITLE
Cambio en UI

### ISSUE THREAD

**Issue by pipehnz** [oscarsanchezcalle/clima-app-react-redux#1]
Hola Oscar, no es un issue pero me gustaría colaborar en tu proyecto cambiándole la interfaz, ¿Què te parece?

**Comment by oscarsanchezcalle** [comment]
Hola Felipe, muchas gracias por tu deseo de contribuir en el proyecto academico de react-redux.

**Comment by oscarsanchezcalle** [comment]
Hola Felipe, te comparto la acción donde se gestiona el proyecto. https://github.com/oscarsanchezcalle/clima-app-react-redux/projects/1#card-25152439
